NESJI-1: initial commit
NesloTechnologies/jira-api pull request #1
Opened 2024-04-04 10:28 UTC by noydb

2024-04-04 10:40 UTC, noydb commented
I will sort out circleci and heroku once this is merged. just to keep the PR as small as possible

2024-04-04 11:12 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/service/ContributorService.java
> +            for (final var contributor : contributors) {
I haven't tried to do it the other way, I haven't investigated the API for that. I thought this was better so only people actually actively engaging in the sprint, will be displayed. The counter to that is if someone has no tickets assigned to them, they won't appear in the list, but I don't think that's too big of a problem. cuz for example if someone isn't in the list and we know they have work to do, it'll be very obvious

2024-04-04 11:13 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/service/ContributorService.java
> +                    continue outer;
:( 

I know sonar and the IDE discourage this, but in this scenario, it makes sense to me to use it. I don't want to break the inner loop and let the logic below run, I want to stop immediately and continue outer.

I think what it indicates is that the method as a whole should be refactored, which is shap, I've said as much in a todo comment as well

2024-04-04 11:18 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/jira/api/service/ContributorService.java
> +            for (final var contributor : contributors) {
Ok but in the long term we would know who is participating in the sprint based on their commitments? Just asking because I think as it stands, I was in the list of sprint contributors even though I don't have a contribution to make this sprint.

Second to this point it might make this logic easier to write and understand and when we decide how we want to capture commitments we can just mask the "uncommitted" contributors if that makes sense? Maybe just a consideration to make but I'm happy with this logic for now if you're apposed to changing it right now.

2024-04-04 11:19 UTC, colsen-neslo commented on src/main/java/za/co/neslotech/jira/api/service/ContributorService.java
> +                    continue outer;
Ye I didn't even know we could do something like this

2024-04-04 11:20 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/domain/JiraIssue.java
> +    private BigDecimal storyPoints;
When mapping the result from the Jira API back to a JSONObject, the type is BigDecimal:
<img width="488" alt="Screenshot 2024-04-04 at 13 19 42" src="https://github.com/NesloTechnologies/jira-api/assets/46442564/bcbe40bb-0ed2-40e1-97e8-b3c1bd4270ac">

2024-04-04 11:30 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/service/ContributorService.java
> +            for (final var contributor : contributors) {
Sweet happy. We can definitely think this through more, I'm sure we'll find a more optimal way, because requests are quite slow too (5-10 seconds for ehub, 20 seconds for neslo app)

This is a POC I guess. 😂  we can definitely improve this

2024-04-04 20:18 UTC, JOlsen-Neslo requested changes

2024-04-04 20:18 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/jira/api/service/ContributorService.java
> +    private List<SprintContributor> convertToList(final List<JiraIssue> issues) {
I think this whole method can be improved on quite a bit, not only in readability but in performance.

I would also use streams to manage and collect this data, should be much faster since the double for loops will be quite inefficient. This would result in a time complexity of O(N^2) since we will be increasing the number of iterations as the contributors list grows

Try something like this:

```java
issues.stream()
            .filter(Objects::nonNull)
            .collect(Collectors.groupingBy(JiraIssue::getAssigneeEmail))
            .entrySet().stream()
            .map(entry -> new SprintContributor(entry.getKey(), entry.getValue()))
            .collect(Collectors.toList());
```

So this way we can let the stream manage the grouping of all issues by assignee email and then iterate over each entry in the map and create a contributor object for each. This way we can achieve a time complexity of O(N) by only iterating over a single list, one time. I think its also easier to read, performance improvements aside.

Only thing is you would then need to add a new constructor to accept a list of issues when creating a contributor

P.S: you can slap in a parallel stream in there if you're feeling sweaty

2024-04-04 20:18 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/jira/api/service/IssueService.java
> +    public BigDecimal getStoryPointEstimate(final HashMap<String, Object> issue) {
Can you code to the interface here?

2024-04-04 20:18 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/jira/api/service/IssueService.java
> +        final var issueFields = (HashMap<String, Object>) issue.get(FIELDS);
Things like this make me feel like we can actually create POJO's that this funky data can map to

2024-04-04 20:18 UTC, JOlsen-Neslo commented on src/main/java/za/co/neslotech/jira/api/service/IssueService.java
> +            if (issueType.equals("story")) {
flip the equals

2024-04-05 06:29 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/service/ContributorService.java
> +    private List<SprintContributor> convertToList(final List<JiraIssue> issues) {
Can we rather do this later on? There's lots of refactoring I want to do which will basically overhaul most of this logic. I just want to get a POC up so we can start using this

2024-04-05 06:29 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/service/IssueService.java
> +    public BigDecimal getStoryPointEstimate(final HashMap<String, Object> issue) {
Not sure what you mean?

2024-04-05 06:29 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/service/IssueService.java
> +        final var issueFields = (HashMap<String, Object>) issue.get(FIELDS);
Ya again I'm kinda doing whatever is easiest to get v1 done for now

2024-04-05 07:16 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/kit/HttpClient.java
> +                .bodyToMono(String.class);
I like having a separate one for query params. Not sure how we would do this otherwise?

2024-04-05 07:37 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/domain/SprintContributor.java
> +        this.addIssue(issue);
Technically will/should never be null at this point

2024-04-10 06:59 UTC, noydb commented on src/main/java/za/co/neslotech/jira/api/service/ContributorService.java
> +    private List<SprintContributor> convertToList(final List<JiraIssue> issues) {
I've applied this, very very nice solution thank you

2024-04-11 10:49 UTC, merged